apiVersion: rds.aws.upbound.io/v1beta1
kind: Instance
metadata:
  name: testing2
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    crossplane.io/external-name: platform-prod-crossplane-testing2
  labels:
    platform.example.org/database: testing2
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
    identifier: platform-prod-crossplane-testing2
    engine: postgres
    storageEncrypted: true
    manageMasterUserPassword: true
    backupRetentionPeriod: 7
    deletionProtection: true
    skipFinalSnapshot: false
    finalSnapshotIdentifier: platform-prod-crossplane-testing2-final
    dbSubnetGroupNameRef:
      name: testing2-subnets
    vpcSecurityGroupIdRefs:
    - name: testing2-db
    dbName: appdb2
    username: dbadmin
    instanceClass: db.t3.micro
    allocatedStorage: 20
    storageType: gp3
    publiclyAccessible: false
    multiAz: true
    autoMinorVersionUpgrade: true
