apiVersion: ec2.aws.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: testing-postgres
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
  labels:
    platform.example.org/database: testing
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
    type: ingress
    fromPort: 5432
    toPort: 5432
    protocol: tcp
    securityGroupIdRef:
      name: testing-db
    sourceSecurityGroupId: sg-0ed0db46108e89fdc
