apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: testing-subnets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    crossplane.io/external-name: platform-prod-crossplane-testing-subnets
  labels:
    platform.example.org/database: testing
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: aws
  forProvider:
    region: us-east-1
    description: Private database subnets
    subnetIds: ["subnet-0e866758d720de56b","subnet-0188bf582f56dc547"]
    tags:
      crossplane-owner: platform-prod
