apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.name }}
  description: PostgreSQL database provisioned through Crossplane.
  annotations:
    backstage.io/kubernetes-label-selector: platform.example.org/database=${{ values.name }}
  links:
    - title: AWS RDS console
      url: "https://console.aws.amazon.com/rds/home?region=${{ values.region }}#databases:"
spec:
  type: database
  owner: group:default/platform-team
