apiVersion: rds.aws.upbound.io/v1beta1
kind: Cluster
metadata:
  name: ${{ values.name }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    crossplane.io/external-name: platform-prod-crossplane-${{ values.name }}
  labels:
    platform.example.org/database: ${{ values.name }}
spec:
  deletionPolicy: Orphan
  providerConfigRef:
    name: aws
  forProvider:
    region: ${{ values.region }}
    engine: aurora-postgresql
    storageEncrypted: true
    manageMasterUserPassword: true
    backupRetentionPeriod: 7
    deletionProtection: true
    skipFinalSnapshot: false
    finalSnapshotIdentifier: platform-prod-crossplane-${{ values.name }}-final
    dbSubnetGroupNameRef:
      name: ${{ values.name }}-subnets
    vpcSecurityGroupIdRefs:
    - name: ${{ values.name }}-db
    databaseName: ${{ values.databaseName }}
    masterUsername: dbadmin
