apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- project.yaml
- applications/backstage.yaml
- applications/crossplane-api.yaml
- applications/crossplane-config.yaml
- applications/crossplane-providers.yaml
- applications/database-requests.yaml
