app:
  title: Internal Developer Portal
  baseUrl: ${BACKSTAGE_BASE_URL}

backend:
  baseUrl: ${BACKSTAGE_BASE_URL}

  listen:
    port: 7007
    host: 0.0.0.0

  cors:
    origin: ${BACKSTAGE_BASE_URL}
    credentials: true

  csp:
    default-src:
      - "'self'"
    base-uri:
      - "'self'"
    font-src:
      - "'self'"
      - "https:"
      - "data:"
    frame-ancestors:
      - "'self'"
    img-src:
      - "'self'"
      - "data:"
    object-src:
      - "'none'"
    script-src:
      - "'self'"
      - "'unsafe-eval'"
    script-src-attr:
      - "'none'"
    style-src:
      - "'self'"
      - "https:"
      - "'unsafe-inline'"
    connect-src:
      - "'self'"
      - "http:"
      - "https:"
    upgrade-insecure-requests: false

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
        - Template
        - Group
        - User
        - Domain

  locations:
    - type: url
      target: https://raw.githubusercontent.com/JohnMonteir0/idp-with-backstage/main/catalog/catalog-info.yaml