# kubernetes/backstage-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  BACKSTAGE_BASE_URL: aHR0cDovL2JhY2tzdGFnZS1wcm9kLjEwNzM2MzIzNzU0Mi5tb250bGFiei5jb20K
  GITHUB_TOKEN: Z2l0aHViX3BhdF8xMUFWQ0RJNUEwZ0JHZ2VtSTd2SmZjX09ndnNhbGRSTzRjaHUyVld5aUNEVkI1MjkwcUFMSmkyZ3JVN1g0N0xnQzFYUk1RTVQ3Vkg4U0JyZm5JCg==
