apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
  annotations:
    external-dns.alpha.kubernetes.io/hostname: backstage-dev.107363237542.montlabz.com
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
    external-dns.kubernetes.io/hostname: backstage-dev.107363237542.montlabz.com
    external-dns.kubernetes.io/cloudflare-proxied: 'false'
    ingress.cilium.io/loadbalancer-mode: shared
    ingress.cilium.io/force-https: disabled
    ingress.cilium.io/backend-service-port: http
spec:
  ingressClassName: cilium
  rules:
  - host: backstage-dev.107363237542.montlabz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backstage
            port:
              number: 7007
