apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: backstage
spec:
  storageClassName: ebs-csi
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2G