apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secrets
  namespace: backstage
$patch: delete
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secrets
  namespace: backstage
$patch: delete
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backstage
  namespace: backstage
$patch: delete
