apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: backstage
spec:
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 384Mi
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "backstage"]
            initialDelaySeconds: 5
            periodSeconds: 5
