apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: aws-ec2
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-aws-ec2
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::REPLACE_ACCOUNT_ID:role/crossplane-databases
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
          - name: package-runtime
            securityContext:
              allowPrivilegeEscalation: false
          securityContext:
            fsGroup: 2000
